USE [W_GnBD]
ALTER INDEX ALL ON GQTPRPIN
REBUILD;
ALTER INDEX ALL ON GQTLOCATIONEXTENSION
REBUILD;
ALTER INDEX ALL ON GQTLOCATION
REBUILD;
ALTER INDEX ALL ON GQTDISPATCHLINE
REBUILD;
ALTER INDEX ALL ON GQTRECEIPTLINE
REBUILD;
ALTER INDEX ALL ON GQTATTACHMENT
REBUILD;
ALTER INDEX ALL ON GQTUSERS
REBUILD;
ALTER INDEX ALL ON GQTSHITY
REBUILD;
ALTER INDEX ALL ON GQTTABPR
REBUILD;
ALTER INDEX ALL ON GQTCATEGORIAS
REBUILD;
ALTER INDEX ALL ON GQTEVCAT
REBUILD;
ALTER INDEX ALL ON GQTCONTA
REBUILD;
ALTER INDEX ALL ON GQTPRODUCT
REBUILD;
ALTER INDEX ALL ON GQTTPCON
REBUILD;
ALTER INDEX ALL ON GQTGENRE
REBUILD;
ALTER INDEX ALL ON GQTAFINI
REBUILD;
ALTER INDEX ALL ON GQTSTAKE
REBUILD;
ALTER INDEX ALL ON GQTREGIS
REBUILD;
ALTER INDEX ALL ON GQTKINDOFEQUIPMENT
REBUILD;
ALTER INDEX ALL ON GQTPEDID
REBUILD;
ALTER INDEX ALL ON GQTLNHAG
REBUILD;
ALTER INDEX ALL ON GQTOUTPT
REBUILD;
ALTER INDEX ALL ON GQTOUTPU
REBUILD;
ALTER INDEX ALL ON GQTPHOTO
REBUILD;
ALTER INDEX ALL ON GQTCOMPANY
REBUILD;
ALTER INDEX ALL ON GQTENTITY
REBUILD;
ALTER INDEX ALL ON GQTFACILITYTYPE
REBUILD;
ALTER INDEX ALL ON GQTOUDOC
REBUILD;
ALTER INDEX ALL ON GQTLENDI
REBUILD;
ALTER INDEX ALL ON GQTSTRAT
REBUILD;
ALTER INDEX ALL ON GQTTPPRO
REBUILD;
ALTER INDEX ALL ON GQTGAMES
REBUILD;
ALTER INDEX ALL ON GQTROOMS
REBUILD;
ALTER INDEX ALL ON GQTSPACE
REBUILD;
ALTER INDEX ALL ON GQTTEAMP
REBUILD;
ALTER INDEX ALL ON GQTDISPATCH
REBUILD;
ALTER INDEX ALL ON GQTPATIENT
REBUILD;
ALTER INDEX ALL ON GQTITEMC
REBUILD;
ALTER INDEX ALL ON GQTMANUALTOCOLLECT
REBUILD;
ALTER INDEX ALL ON GQTASSETMANUAL
REBUILD;
ALTER INDEX ALL ON GQTCNTRY
REBUILD;
ALTER INDEX ALL ON GQTGITEM
REBUILD;
ALTER INDEX ALL ON GQTLDENT
REBUILD;
ALTER INDEX ALL ON GQTESPPE
REBUILD;
ALTER INDEX ALL ON GQTSPECI
REBUILD;
ALTER INDEX ALL ON GQTREPAR
REBUILD;
ALTER INDEX ALL ON GQTINDOC
REBUILD;
ALTER INDEX ALL ON GQTLANGU
REBUILD;
ALTER INDEX ALL ON GQTTRADU
REBUILD;
ALTER INDEX ALL ON GQTANEXD
REBUILD;
ALTER INDEX ALL ON GQTFAMIL
REBUILD;
ALTER INDEX ALL ON GQTTPEQU
REBUILD;
ALTER INDEX ALL ON GQTMOVIM
REBUILD;
ALTER INDEX ALL ON GQTORGAN
REBUILD;
ALTER INDEX ALL ON GQTDECOM
REBUILD;
ALTER INDEX ALL ON GQTPROPR
REBUILD;
ALTER INDEX ALL ON GQTPROJE
REBUILD;
ALTER INDEX ALL ON GQTPWCOM
REBUILD;
ALTER INDEX ALL ON GQTCMPKI
REBUILD;
ALTER INDEX ALL ON GQTLNHDE
REBUILD;
ALTER INDEX ALL ON GQTPWREG
REBUILD;
ALTER INDEX ALL ON GQTPWORG
REBUILD;
ALTER INDEX ALL ON GQTDESAM
REBUILD;
ALTER INDEX ALL ON GQTAERO
REBUILD;
ALTER INDEX ALL ON GQTFTGRI
REBUILD;
ALTER INDEX ALL ON GQTGRID
REBUILD;
ALTER INDEX ALL ON GQTLNHPD
REBUILD;
ALTER INDEX ALL ON GQTFEECA
REBUILD;
ALTER INDEX ALL ON GQTEQUIP
REBUILD;
ALTER INDEX ALL ON GQTUICOM
REBUILD;
ALTER INDEX ALL ON GQTNOTIF
REBUILD;
ALTER INDEX ALL ON GQTSALE
REBUILD;
ALTER INDEX ALL ON GQTINSTA
REBUILD;
ALTER INDEX ALL ON GQTRULES
REBUILD;
ALTER INDEX ALL ON GQTWPESS
REBUILD;
ALTER INDEX ALL ON GQTVISIT
REBUILD;
ALTER INDEX ALL ON GQTMESSAGES
REBUILD;
ALTER INDEX ALL ON GQTPARAMETER
REBUILD;
ALTER INDEX ALL ON GQTASSETPARAMETER
REBUILD;
ALTER INDEX ALL ON GQTFACILITY
REBUILD;
ALTER INDEX ALL ON GQTASSET
REBUILD;
ALTER INDEX ALL ON GQTSALES
REBUILD;
ALTER INDEX ALL ON GQTADDRESS
REBUILD;
ALTER INDEX ALL ON GQTPERIOD
REBUILD;
ALTER INDEX ALL ON GQTREGIO
REBUILD;
ALTER INDEX ALL ON GQTADDRL
REBUILD;
ALTER INDEX ALL ON GQTAGREG
REBUILD;
ALTER INDEX ALL ON GQTEXPEN
REBUILD;
ALTER INDEX ALL ON GQTPERSON
REBUILD;
ALTER INDEX ALL ON GQTYEAR
REBUILD;
ALTER INDEX ALL ON GQTFLDS
REBUILD;
ALTER INDEX ALL ON GQTDATATYPES
REBUILD;
ALTER INDEX ALL ON GQTRECEIPT
REBUILD;
ALTER INDEX ALL ON GQTRORDF
REBUILD;
ALTER INDEX ALL ON GQTRORDI
REBUILD;
ALTER INDEX ALL ON GQTROGL1
REBUILD;
ALTER INDEX ALL ON GQTROIGF
REBUILD;
ALTER INDEX ALL ON GQTROIGI
REBUILD;
ALTER INDEX ALL ON GQTGRPB
REBUILD;
ALTER INDEX ALL ON GQTTBLB
REBUILD;
ALTER INDEX ALL ON GQTTBLK
REBUILD;
ALTER INDEX ALL ON GQTTRSB
REBUILD;
ALTER INDEX ALL ON GQTWAREH
REBUILD;
ALTER INDEX ALL ON GQTITEM
REBUILD;
ALTER INDEX ALL ON GQTCFAQS
REBUILD;
ALTER INDEX ALL ON GQTFAQS
REBUILD;
ALTER INDEX ALL ON GQTAUDIT
REBUILD;
ALTER INDEX ALL ON GQTROLE
REBUILD;
ALTER INDEX ALL ON GQTINPGR
REBUILD;
ALTER INDEX ALL ON GQTCMPNY
REBUILD;
ALTER INDEX ALL ON GQTGLOB
REBUILD;
ALTER INDEX ALL ON GQTPESSOAS
REBUILD;
ALTER INDEX ALL ON GQTCATTP
REBUILD;
ALTER INDEX ALL ON GQTSBCAT
REBUILD;
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
GO