{
 "title": "Quidgest Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "solution", "label": "Solution", "query": { "query": "label_values(exported_job)" } },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({exported_job=\"$solution\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "User logins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(login_counter_total{exported_job=\"$solution\", exported_instance=~\"$instance\"}[$__interval])",
     "legendFormat": "{{Failed}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(page_load_time_milliseconds_count{exported_job=\"$solution\", exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "App"
    },
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{exported_job=\"$solution\", exported_instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Http"
    }
   ]
  },
  {
   "title": "Response time distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (le) (increase(page_load_time_milliseconds_bucket{exported_job=\"$solution\", exported_instance=~\"$instance\"} [10m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_bytes{exported_job=\"$solution\", exported_instance=~\"$instance\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_time_seconds_total{exported_job=\"$solution\", exported_instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Top 10 total page processing duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (Controller, Action) (last_over_time(page_load_time_milliseconds_sum{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range])))",
     "legendFormat": "{{Controller}}.{{Action}}"
    }
   ]
  },
  {
   "title": "Top 10 page response average duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, avg by(Controller, Action) (last_over_time(page_load_time_milliseconds_sum{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range]) /  clamp_min(last_over_time(page_load_time_milliseconds_count{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range]),1) ))",
     "legendFormat": "{{Controller}}.{{Action}}"
    }
   ]
  },
  {
   "title": "Top 10 total routine processing duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by (ModuleOrSystem, Name, Parameter) (last_over_time(manua_exec_time_milliseconds_sum{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range])))",
     "legendFormat": "{{ModuleOrSystem}}.{{Name}}.{{Parameter}}"
    }
   ]
  },
  {
   "title": "Top 10 routine execution average duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, avg by(ModuleOrSystem, Name, Parameter) (last_over_time(manua_exec_time_milliseconds_sum{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range]) /  clamp_min(last_over_time(manua_exec_time_milliseconds_count{exported_job=\"$solution\", exported_instance=~\"$instance\"} [$__range]),1) ))",
     "legendFormat": "{{ModuleOrSystem}}.{{Name}}.{{Parameter}}"
    }
   ]
  }
 ]
}