
--GQTPRPIN | Ver.: 2007.01
UPDATE [GQTPRPIN]
SET [CODPSW] = NULL
where [CODPSW] in (0);
UPDATE [GQTPRPIN]
SET [CODORGAF] = NULL
where [CODORGAF] in (0);
GO
--GQTLOCATIONEXTENSION | Ver.: 2501
UPDATE [GQTLOCATIONEXTENSION]
SET [CODLOCAT] = NULL
where [CODLOCAT] in (0);
GO
--GQTLOCATION | Ver.: 2501
UPDATE [GQTLOCATION]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [GQTLOCATION]
SET [CODFACIL] = NULL
where [CODFACIL] in (0);
GO
--GQTDISPATCHLINE | Ver.: 2503
UPDATE [GQTDISPATCHLINE]
SET [CODDISPA] = NULL
where [CODDISPA] in (0);
UPDATE [GQTDISPATCHLINE]
SET [CODPRODU] = NULL
where [CODPRODU] in (0);
GO
--GQTRECEIPTLINE | Ver.: 2503
UPDATE [GQTRECEIPTLINE]
SET [CODRECEI] = NULL
where [CODRECEI] in (0);
UPDATE [GQTRECEIPTLINE]
SET [CODPRODU] = NULL
where [CODPRODU] in (0);
UPDATE [GQTRECEIPTLINE]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
GO
--GQTATTACHMENT | Ver.: 2505
UPDATE [GQTATTACHMENT]
SET [CODASSET] = NULL
where [CODASSET] in (0);
GO
--GQTUSERS | Ver.: 2506
UPDATE [GQTUSERS]
SET [CODPSW] = NULL
where [CODPSW] in (0);
UPDATE [GQTUSERS]
SET [CODPERSO] = NULL
where [CODPERSO] in (0);
GO
--GQTTABPR | Ver.: 2507
UPDATE [GQTTABPR]
SET [CODTPEQ1] = NULL
where [CODTPEQ1] in (0);
GO
--GQTEVCAT | Ver.: 2509
UPDATE [GQTEVCAT]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTEVCAT]
SET [CODCATEG] = NULL
where [CODCATEG] in (0);
GO
--GQTCONTA | Ver.: 2514
UPDATE [GQTCONTA]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTCONTA]
SET [CODGENRE] = NULL
where [CODGENRE] in (0);
UPDATE [GQTCONTA]
SET [CODTPCON] = NULL
where [CODTPCON] in (0);
GO
--GQTPRODUCT | Ver.: 2514
UPDATE [GQTPRODUCT]
SET [CODLOCAT] = NULL
where [CODLOCAT] in (0);
UPDATE [GQTPRODUCT]
SET [CODLCEXT] = NULL
where [CODLCEXT] in (0);
GO
--GQTTPCON | Ver.: 2514
UPDATE [GQTTPCON]
SET [CODGENRE] = NULL
where [CODGENRE] in (0);
GO
--GQTLNHAG | Ver.: 2526
UPDATE [GQTLNHAG]
SET [CODPEDID] = NULL
where [CODPEDID] in (0);
UPDATE [GQTLNHAG]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
GO
--GQTOUTPT | Ver.: 2527
UPDATE [GQTOUTPT]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
GO
--GQTOUTPU | Ver.: 2533
UPDATE [GQTOUTPU]
SET [CODOUTPT] = NULL
where [CODOUTPT] in (0);
UPDATE [GQTOUTPU]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
UPDATE [GQTOUTPU]
SET [CODITEM] = NULL
where [CODITEM] in (0);
UPDATE [GQTOUTPU]
SET [CODDOCSD] = NULL
where [CODDOCSD] in (0);
GO
--GQTPHOTO | Ver.: 2534
UPDATE [GQTPHOTO]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
GO
--GQTLENDI | Ver.: 2537
UPDATE [GQTLENDI]
SET [CODPESS1] = NULL
where [CODPESS1] in (0);
UPDATE [GQTLENDI]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
UPDATE [GQTLENDI]
SET [CODPESS2] = NULL
where [CODPESS2] in (0);
GO
--GQTGAMES | Ver.: 2540
UPDATE [GQTGAMES]
SET [CODEQJGC] = NULL
where [CODEQJGC] in (0);
UPDATE [GQTGAMES]
SET [CODEQJGF] = NULL
where [CODEQJGF] in (0);
GO
--GQTITEMC | Ver.: 2544
UPDATE [GQTITEMC]
SET [CODITEM] = NULL
where [CODITEM] in (0);
UPDATE [GQTITEMC]
SET [CODTPCAT] = NULL
where [CODTPCAT] in (0);
GO
--GQTMANUALTOCOLLECT | Ver.: 2546
UPDATE [GQTMANUALTOCOLLECT]
SET [CODKINDE] = NULL
where [CODKINDE] in (0);
GO
--GQTASSETMANUAL | Ver.: 2547
UPDATE [GQTASSETMANUAL]
SET [CODASSET] = NULL
where [CODASSET] in (0);
GO
--GQTLDENT | Ver.: 2561
UPDATE [GQTLDENT]
SET [CODDENTR] = NULL
where [CODDENTR] in (0);
UPDATE [GQTLDENT]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
UPDATE [GQTLDENT]
SET [CODITEM] = NULL
where [CODITEM] in (0);
GO
--GQTESPPE | Ver.: 2563
UPDATE [GQTESPPE]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTESPPE]
SET [CODESPEC] = NULL
where [CODESPEC] in (0);
GO
--GQTREPAR | Ver.: 2565
UPDATE [GQTREPAR]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
UPDATE [GQTREPAR]
SET [CODEMPRE] = NULL
where [CODEMPRE] in (0);
UPDATE [GQTREPAR]
SET [CODESPEC] = NULL
where [CODESPEC] in (0);
UPDATE [GQTREPAR]
SET [CODCATEG] = NULL
where [CODCATEG] in (0);
UPDATE [GQTREPAR]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
GO
--GQTINDOC | Ver.: 2568
UPDATE [GQTINDOC]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
UPDATE [GQTINDOC]
SET [CODEMPRE] = NULL
where [CODEMPRE] in (0);
UPDATE [GQTINDOC]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTINDOC]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
GO
--GQTTRADU | Ver.: 2574
UPDATE [GQTTRADU]
SET [CODIDIO1] = NULL
where [CODIDIO1] in (0);
UPDATE [GQTTRADU]
SET [CODIDIO2] = NULL
where [CODIDIO2] in (0);
GO
--GQTANEXD | Ver.: 2575
UPDATE [GQTANEXD]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
UPDATE [GQTANEXD]
SET [CODLANG] = NULL
where [CODLANG] in (0);
GO
--GQTTPEQU | Ver.: 2580
UPDATE [GQTTPEQU]
SET [CODFAMIL] = NULL
where [CODFAMIL] in (0);
GO
--GQTMOVIM | Ver.: 2581
UPDATE [GQTMOVIM]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
UPDATE [GQTMOVIM]
SET [CODROOMS] = NULL
where [CODROOMS] in (0);
GO
--GQTPROPR | Ver.: 2586
UPDATE [GQTPROPR]
SET [CODTPPRO] = NULL
where [CODTPPRO] in (0);
UPDATE [GQTPROPR]
SET [CODREGIA] = NULL
where [CODREGIA] in (0);
UPDATE [GQTPROPR]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
UPDATE [GQTPROPR]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTPROPR]
SET [CODPAIS1] = NULL
where [CODPAIS1] in (0);
GO
--GQTPROJE | Ver.: 2592
UPDATE [GQTPROJE]
SET [CODYEAR] = NULL
where [CODYEAR] in (0);
GO
--GQTCMPKI | Ver.: 2600
UPDATE [GQTCMPKI]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
UPDATE [GQTCMPKI]
SET [CODTPEQ1] = NULL
where [CODTPEQ1] in (0);
GO
--GQTPWREG | Ver.: 2601
UPDATE [GQTPWREG]
SET [CODPSW] = NULL
where [CODPSW] in (0);
UPDATE [GQTPWREG]
SET [CODREGIA] = NULL
where [CODREGIA] in (0);
GO
--GQTPWORG | Ver.: 2603
UPDATE [GQTPWORG]
SET [CODPSW] = NULL
where [CODPSW] in (0);
UPDATE [GQTPWORG]
SET [CODORGAN] = NULL
where [CODORGAN] in (0);
GO
--GQTGRID | Ver.: 2642
UPDATE [GQTGRID]
SET [CODFTGRI] = NULL
where [CODFTGRI] in (0);
UPDATE [GQTGRID]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
GO
--GQTFEECA | Ver.: 2646
UPDATE [GQTFEECA]
SET [CODFLDS] = NULL
where [CODFLDS] in (0);
GO
--GQTNOTIF | Ver.: 2870
UPDATE [GQTNOTIF]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
GO
--GQTSALE | Ver.: 2880
UPDATE [GQTSALE]
SET [CODORGAN] = NULL
where [CODORGAN] in (0);
GO
--GQTINSTA | Ver.: 2887
UPDATE [GQTINSTA]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
UPDATE [GQTINSTA]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
GO
--GQTWPESS | Ver.: 2891
UPDATE [GQTWPESS]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
GO
--GQTVISIT | Ver.: 2892
UPDATE [GQTVISIT]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
GO
--GQTMESSAGES | Ver.: 2893
UPDATE [GQTMESSAGES]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [GQTMESSAGES]
SET [CODPERSO] = NULL
where [CODPERSO] in (0);
GO
--GQTPARAMETER | Ver.: 2895
UPDATE [GQTPARAMETER]
SET [CODKINDE] = NULL
where [CODKINDE] in (0);
GO
--GQTASSETPARAMETER | Ver.: 2897
UPDATE [GQTASSETPARAMETER]
SET [CODASSET] = NULL
where [CODASSET] in (0);
UPDATE [GQTASSETPARAMETER]
SET [CODKINDE] = NULL
where [CODKINDE] in (0);
UPDATE [GQTASSETPARAMETER]
SET [CODPARAM] = NULL
where [CODPARAM] in (0);
GO
--GQTSALES | Ver.: 2901
UPDATE [GQTSALES]
SET [CODORGAN] = NULL
where [CODORGAN] in (0);
GO
--GQTREGIO | Ver.: 2903
UPDATE [GQTREGIO]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
UPDATE [GQTREGIO]
SET [CODPAIS1] = NULL
where [CODPAIS1] in (0);
GO
--GQTADDRL | Ver.: 2905
UPDATE [GQTADDRL]
SET [PARENTID] = NULL
where [PARENTID] in (0);
GO
--GQTAGREG | Ver.: 2906
UPDATE [GQTAGREG]
SET [CODPROJE] = NULL
where [CODPROJE] in (0);
UPDATE [GQTAGREG]
SET [CODYEAR] = NULL
where [CODYEAR] in (0);
GO
--GQTEXPEN | Ver.: 2906
UPDATE [GQTEXPEN]
SET [CODPROJE] = NULL
where [CODPROJE] in (0);
UPDATE [GQTEXPEN]
SET [CODYEAR] = NULL
where [CODYEAR] in (0);
UPDATE [GQTEXPEN]
SET [CODAGGRE] = NULL
where [CODAGGRE] in (0);
GO
--GQTRECEIPT | Ver.: 2910
UPDATE [GQTRECEIPT]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
GO
--GQTROIGF | Ver.: 2912
UPDATE [GQTROIGF]
SET [CODROGL1] = NULL
where [CODROGL1] in (0);
GO
--GQTROIGI | Ver.: 2912
UPDATE [GQTROIGI]
SET [CODROGL1] = NULL
where [CODROGL1] in (0);
GO
--GQTTBLB | Ver.: 2913
UPDATE [GQTTBLB]
SET [FKEY1] = NULL
where [FKEY1] in (0);
GO
--GQTTBLK | Ver.: 2914
UPDATE [GQTTBLK]
SET [FKEY1] = NULL
where [FKEY1] in (0);
UPDATE [GQTTBLK]
SET [FKEY2] = NULL
where [FKEY2] in (0);
GO
--GQTITEM | Ver.: 3215
UPDATE [GQTITEM]
SET [CODGITEM] = NULL
where [CODGITEM] in (0);
UPDATE [GQTITEM]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
GO
--GQTFAQS | Ver.: 3280
UPDATE [GQTFAQS]
SET [CODCFAQS] = NULL
where [CODCFAQS] in (0);
GO
--GQTCMPNY | Ver.: 3378
UPDATE [GQTCMPNY]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
GO
--GQTGLOB | Ver.: 3378
UPDATE [GQTGLOB]
SET [CODFACTY] = NULL
where [CODFACTY] in (0);
GO
--GQTCATTP | Ver.: 3383
UPDATE [GQTCATTP]
SET [CODSBCAT] = NULL
where [CODSBCAT] in (0);
GO
--GQTAFINI | Ver.: 3711
UPDATE [GQTAFINI]
SET [CODGAFIN] = NULL
where [CODGAFIN] in (0);
UPDATE [GQTAFINI]
SET [CODPESS2] = NULL
where [CODPESS2] in (0);
UPDATE [GQTAFINI]
SET [CODPESS1] = NULL
where [CODPESS1] in (0);
GO
--GQTCITY | Ver.: 3724
UPDATE [GQTCITY]
SET [CODCTRY] = NULL
where [CODCTRY] in (0);
GO
--GQTPROCN | Ver.: 3724
UPDATE [GQTPROCN]
SET [CODPROPE] = NULL
where [CODPROPE] in (0);
GO
--GQTPROPH | Ver.: 3724
UPDATE [GQTPROPH]
SET [CODPROPE] = NULL
where [CODPROPE] in (0);
GO
--GQTPROPE | Ver.: 3732
UPDATE [GQTPROPE]
SET [CODAGENT] = NULL
where [CODAGENT] in (0);
UPDATE [GQTPROPE]
SET [CODCITY] = NULL
where [CODCITY] in (0);
GO
--GQTLNHDE | Ver.: 3798
UPDATE [GQTLNHDE]
SET [CODLNHPD] = NULL
where [CODLNHPD] in (0);
UPDATE [GQTLNHDE]
SET [CODPEDID] = NULL
where [CODPEDID] in (0);
UPDATE [GQTLNHDE]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
UPDATE [GQTLNHDE]
SET [CODLNHAG] = NULL
where [CODLNHAG] in (0);
GO
--GQTLNHDF | Ver.: 3798
UPDATE [GQTLNHDF]
SET [CODLNHDE] = NULL
where [CODLNHDE] in (0);
GO
--GQTLNHPD | Ver.: 3798
UPDATE [GQTLNHPD]
SET [CODPEDID] = NULL
where [CODPEDID] in (0);
UPDATE [GQTLNHPD]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
GO
--GQTAIRPL | Ver.: 3801
UPDATE [GQTAIRPL]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
GO
--GQTAIRPT | Ver.: 3801
UPDATE [GQTAIRPT]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
GO
--GQTBRDPS | Ver.: 3801
UPDATE [GQTBRDPS]
SET [CODFLIGH] = NULL
where [CODFLIGH] in (0);
UPDATE [GQTBRDPS]
SET [CODPSNGR] = NULL
where [CODPSNGR] in (0);
UPDATE [GQTBRDPS]
SET [CODTICKT] = NULL
where [CODTICKT] in (0);
UPDATE [GQTBRDPS]
SET [CODFLTSC] = NULL
where [CODFLTSC] in (0);
GO
--GQTFLIGH | Ver.: 3801
UPDATE [GQTFLIGH]
SET [CODAIRLN] = NULL
where [CODAIRLN] in (0);
UPDATE [GQTFLIGH]
SET [CODAIRPT] = NULL
where [CODAIRPT] in (0);
UPDATE [GQTFLIGH]
SET [CODAIRFR] = NULL
where [CODAIRFR] in (0);
UPDATE [GQTFLIGH]
SET [CODAIRTO] = NULL
where [CODAIRTO] in (0);
GO
--GQTFLTSC | Ver.: 3801
UPDATE [GQTFLTSC]
SET [CODFLIGH] = NULL
where [CODFLIGH] in (0);
GO
--GQTTICKT | Ver.: 3801
UPDATE [GQTTICKT]
SET [CODPSNGR] = NULL
where [CODPSNGR] in (0);
GO
--GQTHPESS | Ver.: 3835
UPDATE [GQTHPESS]
SET [CODPESSO] = NULL
where [CODPESSO] in (0);
UPDATE [GQTHPESS]
SET [CODEMPRE] = NULL
where [CODEMPRE] in (0);
GO
--GQTITEMP | Ver.: 3850
UPDATE [GQTITEMP]
SET [CODITEM] = NULL
where [CODITEM] in (0);
GO
--GQTFACILITY | Ver.: 3875
UPDATE [GQTFACILITY]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [GQTFACILITY]
SET [CODFACTY] = NULL
where [CODFACTY] in (0);
UPDATE [GQTFACILITY]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
GO
--GQTENTITY | Ver.: 3887
UPDATE [GQTENTITY]
SET [FIRSTFACILITIE] = NULL
where [FIRSTFACILITIE] in (0);
UPDATE [GQTENTITY]
SET [LASTFACILITIE] = NULL
where [LASTFACILITIE] in (0);
GO
--GQTFLDS | Ver.: 3902
UPDATE [GQTFLDS]
SET [CODAERO] = NULL
where [CODAERO] in (0);
UPDATE [GQTFLDS]
SET [CODEQUIP] = NULL
where [CODEQUIP] in (0);
GO
--GQTDISPATCH | Ver.: 3921
UPDATE [GQTDISPATCH]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [GQTDISPATCH]
SET [CODDISST] = NULL
where [CODDISST] in (0);
UPDATE [GQTDISPATCH]
SET [CODPERSO] = NULL
where [CODPERSO] in (0);
GO
--GQTEQUIP | Ver.: 3950
UPDATE [GQTEQUIP]
SET [CODEMPRE] = NULL
where [CODEMPRE] in (0);
UPDATE [GQTEQUIP]
SET [CODPESS1] = NULL
where [CODPESS1] in (0);
UPDATE [GQTEQUIP]
SET [CODTPEQU] = NULL
where [CODTPEQU] in (0);
UPDATE [GQTEQUIP]
SET [CODWAREH] = NULL
where [CODWAREH] in (0);
UPDATE [GQTEQUIP]
SET [CODITEM] = NULL
where [CODITEM] in (0);
UPDATE [GQTEQUIP]
SET [CODDECO] = NULL
where [CODDECO] in (0);
UPDATE [GQTEQUIP]
SET [CODROOMS] = NULL
where [CODROOMS] in (0);
GO
--GQTPWCOM | Ver.: 3950
UPDATE [GQTPWCOM]
SET [CODPSW] = NULL
where [CODPSW] in (0);
UPDATE [GQTPWCOM]
SET [CODPESS1] = NULL
where [CODPESS1] in (0);
GO
--GQTPESSOAS | Ver.: 4067
UPDATE [GQTPESSOAS]
SET [CODEMPRE] = NULL
where [CODEMPRE] in (0);
UPDATE [GQTPESSOAS]
SET [CODPARTE] = NULL
where [CODPARTE] in (0);
UPDATE [GQTPESSOAS]
SET [CODCATEG] = NULL
where [CODCATEG] in (0);
UPDATE [GQTPESSOAS]
SET [CODPAISE] = NULL
where [CODPAISE] in (0);
UPDATE [GQTPESSOAS]
SET [CODCNTRY] = NULL
where [CODCNTRY] in (0);
UPDATE [GQTPESSOAS]
SET [CODREGIA] = NULL
where [CODREGIA] in (0);
GO
--GQTASSET | Ver.: 4114
UPDATE [GQTASSET]
SET [CODKINDE] = NULL
where [CODKINDE] in (0);
UPDATE [GQTASSET]
SET [CODMANUF] = NULL
where [CODMANUF] in (0);
GO
--GQTATAGS | Ver.: 4115
UPDATE [GQTATAGS]
SET [CODASSET] = NULL
where [CODASSET] in (0);
GO
--USERAUTHORIZATION | Ver.: 4350
UPDATE [USERAUTHORIZATION]
SET [CODPSW] = NULL
where [CODPSW] in (0);
GO
--ASYNCPROCESS | Ver.: 4353
UPDATE [ASYNCPROCESS]
SET [CODENTIT] = NULL
where [CODENTIT] in (0);
UPDATE [ASYNCPROCESS]
SET [CODPSW] = NULL
where [CODPSW] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--ASYNCPROCESSARGUMENT | Ver.: 4354
UPDATE [ASYNCPROCESSARGUMENT]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO
--ASYNCPROCESSATTACHMENTS | Ver.: 4355
UPDATE [ASYNCPROCESSATTACHMENTS]
SET [CODS_APR] = NULL
where [CODS_APR] in ('00000000-0000-0000-0000-000000000000','{00000000-0000-0000-0000-000000000000}');
GO


